FORMAT: 1A
HOST: https://api.tokyometroapp.jp/api/v2/

# TokyoMetroOpendataAPI
## このドキュメントについて
- 東京メトロが公開しているオープンデータAPIを個人的にまとめたものです。
- [オープンデータ活用コンテスト](http://tokyometro10th.jp/future/opendata/index.html)参加者が参照することを想定しています
- `API Blueprints`で記述され、[apiary.io](http://apiary.io/)によって、ホスティングされています
- [元データ](https://github.com/syotaro/TokyoMetroOpendataAPI/blob/master/apiary.apib)は、github上に保存されています[markdownでプレビューする](https://github.com/syotaro/TokyoMetroOpendataAPI/blob/master/apiary.md)と見やすいです


## このドキュメントから得られる情報
以下を得ることができます

- APIの詳細な仕様
  - Request Parameters
  - Response Parameters
  - Sample Response
- 本番APIに対してリクエストを発行及び結果の取得
- APIからデータを取得する為のコードスニペットを発行する。スニペットの形式は、12の言語、形式(JavaScript,Raw,cURL,Node.js,Python,PHP,Ruby,C#,Visual,Groovy,Objective-C,Swift)に対応する

## 本番APIへのリクエスト発行手順

- 以下、駅時刻表を取得する例
- 「xxxxxxxxxxxxxxxxxxx」の部分には、自身のアクセストークンを記入する

![](http://s3img.jp/20140921151100.png)


# Group メトロデータ取得・検索API

## 駅時刻表 [/datapoints?rdf:type=odpt:StationTimetable&acl%3AconsumerKey={acl%3AconsumerKey}&odpt:station={odpt%3Astation}]
各駅の平日、土曜、休日の列車着時刻、発車時刻と種別を表す。

+ Parameters
    + rdf%3Atype                    (required, odpt:StationTimetable, `odpt:StationTimetable`) ... クラス指定
    + acl%3AconsumerKey             (required, acl:ConsumerKey      , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + %40id                         (optional, URN                  , `optional`) ... 固有識別子(ucode)
    + owl%3AsameAs                  (optional, URL                  , `optional`) ... 固有識別子。命名ルールは、odpt.StationTimetable:TokyoMetro.路線名.駅名.方面名 である。
    + odpt%3Astation                (optional, odpt:Station         , `odpt.Station:TokyoMetro.Hanzomon.OmoteSando`) ... 駅
    + odpt%3Arailway                (optional, odpt:Railway         , `optional`) ... 路線
    + odpt%3Aoperator               (optional, odpt:Operator        , `optional`) ... 運行会社
    + odpt%3ArailDirection          (optional, odpt:RailDirection   , `optional`) ... 方面


### Response [GET]
#### Response Params

odpt:StationTimetable プロパティ        | 値域                               | 説明                                                                                                                                                                                          | 必須
----------------------------            | -----------------------            | ------------------------------------------------------------------------------------------------------------------------------                                                                | -----
@context                                | URL                                | JSON-LD仕様に基づく @context のURL                                                                                                                                                            | ◯
@id                                     | URN                                | 固有識別子(ucode)                                                                                                                                                                             | ◯
@type                                   | odpt:StationTimetable              | クラス指定                                                                                                                                                                                    | ◯
owl:sameAs                              | URL                                | 固有識別子。命名ルールは、odpt.StationTimetable:TokyoMetro.路線名.駅名.方面名 である。                                                                                                        | ◯
dc:date                                 | xsd:dateTime                       | データ生成時刻、e.g. 2013–01–13T15:10:00+09:00、ISO8601日付時刻形式                                                                                                                         | ◯
odpt:station                            | odpt:Station                       | 駅                                                                                                                                                                                            | ◯
odpt:railway                            | odpt:Railway                       | 路線                                                                                                                                                                                          | ◯
odpt:operator                           | odpt:Operator                      | 運行会社                                                                                                                                                                                      | ◯
odpt:railDirection                      | odpt:RailDirection                 | 方面                                                                                                                                                                                          | ◯
odpt:weekdays                           | Array(odpt:StationTimetableObject) | 平日（出発時間、行き先駅名等の組のリストを格納）                                                                                                                                              |
odpt:saturdays                          | Array(odpt:StationTimetableObject) | 土曜日（出発時間、行き先駅名等の組のリストを格納）                                                                                                                                            |
odpt:holidays                           | Array(odpt:StationTimetableObject) | 休日（出発時間、行き先駅名等の組のリストを格納）                                                                                                                                              |

odpt:StationTimetableObject::プロパティ | 値域                               | 説明                                                                                                                                                                                          | 必須
----------------------------            | -----------------------            | ------------------------------------------------------------------------------------------------------------------------------                                                                | -----
odpt:departureTime                      | odpt:Time                          | 出発時間 (ISO8601時刻形式, e.g. 05:09)                                                                                                                                                        | ◯
odpt:destinationStation                 | odpt:Station                       | 行き先駅                                                                                                                                                                                      | ◯
odpt:trainType                          | odpt:TrainType                     | 列車種別。各停(odpt.TrainType:Local)、急行(odpt.TrainType:Express)、快速(odpt.TrainType:Rapid)、特急(odpt.TrainType:LimitedExpress)など。                                                     | ◯
odpt:isLast                             | xsd:boolean                        | 最終電車の場合、true。最終電車でない場合は省略。                                                                                                                                              |
odpt:isOrigin                           | xsd:boolean                        | 始発駅の場合、true。始発駅ではない場合は省略。                                                                                                                                                |
odpt:carComposition                     | xsd:integer                        | 車両数（駅に停車する車両数が列車毎に異なる場合に格納される）。                                                                                                                                |
odpt:note                               | xsd:string                         | その他の注釈（接続、通過待ちなど）。                                                                                                                                                          |

+ Response 200 (application/json)
    + Body

            [
              {
                "@id": "urn:ucode:_00001C000000000000010000030C3D7E",
                "@type": "odpt:StationTimetable",
                "@context": "http://vocab.tokyometroapp.jp/context_odpt_StationTimetable.jsonld",
                "owl:sameAs": "odpt.StationTimetable:TokyoMetro.Tozai.Otemachi.Nakano",
                "odpt:station": "odpt.Station:TokyoMetro.Tozai.Otemachi",
                "odpt:railway": "odpt.Railway:TokyoMetro.Tozai",
                "odpt:operator": "odpt.Operator:TokyoMetro",
                "odpt:railDirection": "odpt.RailDirection:TokyoMetro.Nakano",
                "dc:date": "2014-08-25T21:16:03+09:00",
                "odpt:weekdays": [
                  {
                    "odpt:departureTime": "05:09",
                    "odpt:destinationStation": "odpt.Station:TokyoMetro.Tozai.Nakano",
                    "odpt:trainType": "odpt.TrainType:TokyoMetro.Local"
                  },
                  {
                    "odpt:departureTime": "05:18",
                    "odpt:destinationStation": "odpt.Station:TokyoMetro.Tozai.Nakano",
                    "odpt:trainType": "odpt.TrainType:TokyoMetro.Local"
                  },
                  {
                    "odpt:departureTime": "05:30",
                    "odpt:destinationStation": "odpt.Station:TokyoMetro.Tozai.Nakano",
                    "odpt:trainType": "odpt.TrainType:TokyoMetro.Local"
                  },
                  {
                    "odpt:departureTime": "05:36",
                    "odpt:destinationStation": "odpt.Station:TokyoMetro.Tozai.Nakano",
                    "odpt:trainType": "odpt.TrainType:TokyoMetro.Local"
                  },
                  {
                    "odpt:departureTime": "05:48",
                    "odpt:destinationStation": "odpt.Station:TokyoMetro.Tozai.Nakano",
                    "odpt:trainType": "odpt.TrainType:TokyoMetro.Local"
                  },
                  {
                    "odpt:departureTime": "05:44",
                    "odpt:destinationStation": "odpt.Station:JR-East.Chuo.Mitaka",
                    "odpt:trainType": "odpt.TrainType:TokyoMetro.Local"
                  },
                  "odpt:saturdays": [],
                  "odpt:holidays": []
                ]
              }
            ]

## 列車運行情報 [/datapoints?rdf:type=odpt:TrainInformation&acl%3AconsumerKey={acl%3AconsumerKey}]
列車運行情報を示す。基本的に発生時刻、発生箇所、現在状況を示す。平常運転時でも「平常」などの文字列を含んだ文字列を返す。 平常時かそれ以外かは、odpt:trainInformationStatus プロパティの存在有無で判定可能である。

+ Parameters
    + rdf%3Atype                    (required, odpt:TrainInformation, `odpt:TrainInformation`) ... クラス指定
    + acl%3AconsumerKey             (required, acl:ConsumerKey      , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + %40id                         (optional, URN                  , `optional`) ... 固有識別子(ucode)
    + odpt%3Aoperator               (optional, odpt:Operator        , `optional`) ... 運行会社
    + odpt%3Arailway                (optional, odpt:Railway         , `optional`) ... 発生路線
    + odpt%3AtrainInformationStatus (optional, xsd:string           , `optional`) ... 平常時は省略。運行情報が存在する場合は「運行情報あり」を格納。遅延などの情報を取得可能な場合は、「遅延」等のテキストを格納。
    + odpt%3AtrainInformationText   (optional, xsd:string           , `optional`) ... 運行情報テキスト

### Response [GET]
#### Response Params

Properties                              | 値域                               | 説明                                                                                                                                                                                          | 必須
----------------------------            | -----------------------            | ------------------------------------------------------------------------------------------------------------------------------                                                                | -----
@context                                | URL                                | JSON-LD仕様に基づく @context のURL                                                                                                                                                            | ◯
@id                                     | URN                                | 固有識別子(ucode)                                                                                                                                                                             | ◯
@type                                   | odpt:TrainInformation              | クラス指定                                                                                                                                                                                    | ◯
dc:date                                 | xsd:dateTime                       | データ生成時刻、e.g. 2013–01–13T15:10:00+09:00、ISO8601 日付時刻形式                                                                                                                        | ◯
dct:valid                               | xsd:dateTime                       | 有効期限（ISO8601 日付時刻形式）                                                                                                                                                              | ◯
odpt:operator                           | odpt:Operator                      | 運行会社                                                                                                                                                                                      | ◯
odpt:timeOfOrigin                       | xsd:dateTime                       | 発生時刻（ISO8601 日付時刻形式）                                                                                                                                                              | ◯
odpt:railway                            | odpt:Railway                       | 発生路線                                                                                                                                                                                      | ◯
odpt:trainInformationStatus             | xsd:string                         | 平常時は省略。運行情報が存在する場合は「運行情報あり」を格納。遅延などの情報を取得可能な場合は、「遅延」等のテキストを格納。                                                                  |
odpt:trainInformationText               | xsd:string                         | 運行情報テキスト                                                                                                                                                                              | ◯

+ Response 200 (application/json)
    + Body

            [
              {
                "@context": "http://vocab.tokyometroapp.jp/context_odpt_train.jsonld",
                "@type": "odpt:Train",
                "@id": "urn:ucode:_00001C000000000000010000030CA20F",
                "dc:date": "2014-09-20T23:27:45+09:00",
                "dct:valid": "2014-09-20T23:29:15+09:00",
                "odpt:frequency": 90,
                "odpt:railway": "odpt.Railway:TokyoMetro.Marunouchi",
                "owl:sameAs": "odpt.Train:TokyoMetro.Marunouchi.A2311",
                "odpt:trainNumber": "A2311",
                "odpt:trainType": "odpt.TrainType:TokyoMetro.Local",
                "odpt:delay": 0,
                "odpt:startingStation": "odpt.Station:TokyoMetro.Marunouchi.Ikebukuro",
                "odpt:terminalStation": "odpt.Station:TokyoMetro.Marunouchi.Ogikubo",
                "odpt:fromStation": "odpt.Station:TokyoMetro.Marunouchi.Ikebukuro",
                "odpt:toStation": "odpt.Station:TokyoMetro.Marunouchi.ShinOtsuka",
                "odpt:railDirection": "odpt.RailDirection:TokyoMetro.Ogikubo",
                "odpt:trainOwner": "odpt.TrainOwner:TokyoMetro"
              }
            ]


## 列車ロケーション情報 [/datapoints?rdf:type=odpt:Train&acl%3AconsumerKey={acl%3AconsumerKey}]
列車の在線位置を表す。列車ロケーション情報は、駅にいる状態（odpt:fromStation のみ値が存在）、「駅間を走行中」という状態（odpt:fromStation, odpt:toStation の両方に値が存在）を用いた相対位置情報表記に対応する。

列車ロケーション情報は、始発から終電まで、列車が運行している時間帯に取得可能である。

始発駅や終着駅には、東京メトロ以外の駅名が出現する場合があるが、他社の駅時刻表や駅情報等は提供しない。

+ Parameters
    + rdf%3Atype                    (required, odpt:TrainInformation, `odpt:TrainInformation`) ... クラス指定
    + acl%3AconsumerKey             (required, acl:ConsumerKey      , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + %40id                           (optional, URN                  ,  `optional`) ... 固有識別子(ucode)
    + owl%3AsameAs                  (optional, URL                  ,  `optional`) ... 固有識別子。命名ルールは、odpt.Train:TokyoMetro.路線名.列車番号である。
    + odpt%3AtrainNumber            (optional, xsd:string           ,  `optional`) ... 列車番号
    + odpt%3AtrainType              (optional, odpt:TrainType       ,  `optional`) ... 列車種別。各停(odpt.TrainType:Local)、急行(odpt.TrainType:Express)、快速(odpt.TrainType:Rapid)、特急(odpt.TrainType:LimitedExpress)など。
    + odpt%3Arailway                (required, odpt:Railway         ,  `odpt.Railway:TokyoMetro.Chiyoda`) ... 鉄道路線
    + odpt%3AtrainOwner             (optional, odpt:TrainOwner      ,  `optional`) ... 車両の所属会社
    + odpt%3ArailDirection          (optional, odpt:RailDirection   ,  `optional`) ... 方面（渋谷方面行きodpt.RailDirection:TokyoMetro.Shibuyaなど。）
    + odpt%3Adelay                  (optional, xsd:integer          ,  `optional`) ... 遅延時間（秒）
    + odpt%3AstartingStation        (optional, odpt:Station         ,  `optional`) ... 列車の始発駅
    + odpt%3AterminalStation        (optional, odpt:Station         ,  `optional`) ... 列車の終着駅
    + odpt%3AfromStation            (optional, odpt:Station         ,  `optional`) ... 列車が出発した駅
    + odpt%3AtoStation              (optional, odpt:Station         ,  `optional`) ... 列車が向かっている駅


### Response [GET]
#### Response Params

Properties                              | 値域                               | 説明                                                                                                                                                                                          | 必須
----------------------------            | -----------------------            | ------------------------------------------------------------------------------------------------------------------------------                                                                | -----
@context                                | URL                                | JSON-LD仕様に基づく @context のURL                                                                                                                                                            | ◯
@id                                     | URN                                | 固有識別子(ucode)                                                                                                                                                                             | ◯
@type                                   | odpt:Train                         | クラス指定                                                                                                                                                                                    | ◯
owl:sameAs                              | URL                                | 固有識別子。命名ルールは、odpt.Train:TokyoMetro.路線名.列車番号である。                                                                                                                       | ◯
odpt:trainNumber                        | xsd:string                         | 列車番号                                                                                                                                                                                      | ◯
odpt:trainType                          | odpt:TrainType                     | 列車種別。各停(odpt.TrainType:Local)、急行(odpt.TrainType:Express)、快速(odpt.TrainType:Rapid)、特急(odpt.TrainType:LimitedExpress)など。                                                     | ◯
dc:date                                 | xsd:dateTime                       | データ生成時刻、e.g. 2013–01–13T15:10:00+09:00、ISO8601 日付時刻形式                                                                                                                        | ◯
dct:valid                               | xsd:dateTime                       | データ保証期限、e.g. 2013–01–13T15:10:00+09:00、ISO8601 日付時刻形式                                                                                                                        | ◯
odpt:frequency                          | xsd:integer                        | 更新頻度（秒）、指定された秒数以降にリクエストを行うことで、最新値が取得される                                                                                                                | ◯
odpt:railway                            | odpt:Railway                       | 鉄道路線ID                                                                                                                                                                                    | ◯
odpt:trainOwner                         | odpt:TrainOwner                    | 車両の所属会社                                                                                                                                                                                | ◯
odpt:railDirection                      | odpt:RailDirection                 | 方面（渋谷方面行きを表すodpt.RailDirection:TokyoMetro.Shibuyaなど）                                                                                                                           | ◯
odpt:delay                              | xsd:integer                        | 遅延時間（秒）。5分未満は切り捨て。                                                                                                                                                           | ◯
odpt:startingStation                    | odpt:Station                       | 列車の始発駅                                                                                                                                                                                  | ◯
odpt:terminalStation                    | odpt:Station                       | 列車の終着駅                                                                                                                                                                                  | ◯
odpt:fromStation                        | odpt:Station                       | 列車が出発した駅                                                                                                                                                                              | ◯
odpt:toStation                          | odpt:Station                       | 列車が向かっている駅                                                                                                                                                                          |

+ Response 200 (application/json)
    + Body

            [
              {
                "@context": "http://vocab.tokyometroapp.jp/context_odpt_train.jsonld",
                "@type": "odpt:Train",
                "@id": "urn:ucode:_00001C000000000000010000030C4D61",
                "dc:date": "2014-09-08T20:53:51+09:00",
                "dct:valid": "2014-09-08T20:54:51+09:00",
                "odpt:frequency": 60,
                "odpt:railway": "odpt.Railway:TokyoMetro.Chiyoda",
                "owl:sameAs": "odpt.Train:TokyoMetro.Chiyoda.A2098S4",
                "odpt:trainNumber": "A2098S4",
                "odpt:trainType": "odpt.TrainType:TokyoMetro.Local",
                "odpt:delay": 0,
                "odpt:startingStation": "odpt.Station:TokyoMetro.Chiyoda.KitaAyase",
                "odpt:terminalStation": "odpt.Station:TokyoMetro.Chiyoda.Ayase",
                "odpt:fromStation": "odpt.Station:TokyoMetro.Chiyoda.KitaAyase",
                "odpt:toStation": null,
                "odpt:railDirection": "odpt.RailDirection:TokyoMetro.Ayase",
                "odpt:trainOwner": "odpt.TrainOwner:TokyoMetro"
              },
              {
                "@context": "http://vocab.tokyometroapp.jp/context_odpt_train.jsonld",
                "@type": "odpt:Train",
                "@id": "urn:ucode:_00001C000000000000010000030C4D65",
                "dc:date": "2014-09-08T20:53:51+09:00",
                "dct:valid": "2014-09-08T20:54:51+09:00",
                "odpt:frequency": 60,
                "odpt:railway": "odpt.Railway:TokyoMetro.Chiyoda",
                "owl:sameAs": "odpt.Train:TokyoMetro.Chiyoda.A2029K",
                "odpt:trainNumber": "A2029K",
                "odpt:trainType": "odpt.TrainType:TokyoMetro.Local",
                "odpt:delay": 0,
                "odpt:startingStation": "odpt.Station:JR-East.Joban.Abiko",
                "odpt:terminalStation": "odpt.Station:TokyoMetro.Chiyoda.YoyogiUehara",
                "odpt:fromStation": "odpt.Station:TokyoMetro.Chiyoda.Yushima",
                "odpt:toStation": null,
                "odpt:railDirection": "odpt.RailDirection:TokyoMetro.YoyogiUehara",
                "odpt:trainOwner": "odpt.TrainOwner:JR-East"
              }
            ]

## 駅情報 [/datapoints?rdf:type=odpt:Station&acl%3AconsumerKey={acl%3AconsumerKey}]
駅情報 odpt:Stationは、駅の情報を示す。この情報は国土交通省国土数値情報を元に、 施設情報や乗り換え路線などを加筆・修正したものとなる。

+ Parameters
    + rdf%3Atype         (required, odpt:Station    , `odpt:Station`) ... クラス指定
    + acl%3AconsumerKey  (required, acl:ConsumerKey , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + @id                (optional, URN             , `optional`) ... 固有識別子(ucode)
    + owl%3AsameAs       (URL                       , `optional`) ... 固有識別子。命名ルールは、odpt.Station:TokyoMetro.路線名.駅名である。
    + dc%3Atitle         (xsd:string                , `optional`) ... 駅名
    + odpt%3Aoperator    (odpt:Operator             , `optional`) ... 運行会社
    + odpt%3Arailway     (odpt:Railway              , `optional`) ... 路線
    + odpt%3AstationCode (xsd:string                , `optional`) ... 駅コード

### Response [GET]
#### Response Params

Properties                              | 値域                               | 説明                                                                                                                                                                                          | 必須
----------------------------            | -----------------------            | ------------------------------------------------------------------------------------                                                                                                          | -----
@context                                | URL                                | JSON-LD仕様に基づく @context のURL                                                                                                                                                            | ◯
@id                                     | URN                                | 固有識別子(ucode)                                                                                                                                                                             | ◯
@type                                   | odpt:Station                       | 地物のクラス名、odpt:Station                                                                                                                                                                  | ◯
owl:sameAs                              | URL                                | 固有識別子。命名ルールは、odpt.Station:TokyoMetro.路線名.駅名である。                                                                                                                         | ◯
dc:title                                | xsd:string                         | 駅名                                                                                                                                                                                          | ◯
dc:date                                 | xsd:dateTime                       | 駅情報の生成時刻(ISO8601 日付時刻形式)                                                                                                                                                        |
geo:long                                | xsd:double                         | 代表点の経度、10進表記                                                                                                                                                                        |
geo:lat                                 | xsd:double                         | 代表点の緯度、10進表記                                                                                                                                                                        |
ug:region                               | odpt:GeoDocument                   | 駅代表点のデータをgeojsonで取得するためのURL。取得にはアクセストークンの付与が必要。                                                                                                          |
odpt:operator                           | odpt:Operator                      | 管理会社                                                                                                                                                                                      | ◯
odpt:railway                            | odpt:Railway                       | 路線                                                                                                                                                                                          | ◯
odpt:connectingRailway                  | Array(odpt:Railway)                | 乗り換え可能路線の一覧                                                                                                                                                                        |
odpt:facility                           | Array(odpt:StationFacility)        | 駅施設を表すオブジェクトのURI                                                                                                                                                                 | ◯
odpt:passengerSurvey                    | Array(odpt:PassengerSurvey)        | 駅乗降人員数を表すオブジェクトへのリンク                                                                                                                                                      | ◯
odpt:stationCode                        | xsd:string                         | 駅コード                                                                                                                                                                                      | ◯
odpt:exit                               | Array(ug:Poi)                      | 駅出入口を表すオブジェクトへのリンク                                                                                                                                                          | ◯

+ Response 200 (application/json)
    + Body

            [
              {
                "@id": "urn:ucode:_00001C000000000000010000030C46CD",
                "@type": "odpt.Station",
                "owl:sameAs": "odpt.Station:TokyoMetro.Hibiya.Ueno",
                "dc:date": "2014-09-03T11:39:51+09:00",
                "dc:title": "上野",
                "ug:region": "https://api.tokyometroapp.jp/api/v2/places/urn:ucode:_00001C000000000000010000030C46CD.geojson",
                "odpt:operator": "odpt.Operator:TokyoMetro",
                "odpt:railway": "odpt.Railway:TokyoMetro.Hibiya",
                "odpt:connectingRailway": [
                  "odpt.Railway:JR-East.Yamanote",
                  "odpt.Railway:JR-East.Utsunomiya",
                  "odpt.Railway:JR-East.Joban",
                  "odpt.Railway:JR-East.Takasaki",
                  "odpt.Railway:JR-East.KeihinTohoku",
                  "odpt.Railway:TokyoMetro.Ginza",
                  "odpt.Railway:Keisei.KeiseiMain"
                ],
                "odpt:facility": "odpt.StationFacility:TokyoMetro.Ueno",
                "odpt:passengerSurvey": [
                  "odpt.PassengerSurvey:TokyoMetro.Ueno.2013",
                  "odpt.PassengerSurvey:TokyoMetro.Ueno.2012",
                  "odpt.PassengerSurvey:TokyoMetro.Ueno.2011"
                ],
                "odpt:stationCode": "H17",
                "odpt:exit": [
                  "urn:ucode:_00001C000000000000010000030C40B4",
                  "urn:ucode:_00001C000000000000010000030C40B5",
                  "urn:ucode:_00001C000000000000010000030C41F9",
                  "urn:ucode:_00001C000000000000010000030C41FA",
                  "urn:ucode:_00001C000000000000010000030C41FB",
                  "urn:ucode:_00001C000000000000010000030C41FC",
                  "urn:ucode:_00001C000000000000010000030C41FD",
                  "urn:ucode:_00001C000000000000010000030C41FE",
                  "urn:ucode:_00001C000000000000010000030C4466",
                  "urn:ucode:_00001C000000000000010000030C4467",
                  "urn:ucode:_00001C000000000000010000030C4468",
                  "urn:ucode:_00001C000000000000010000030C4469",
                  "urn:ucode:_00001C000000000000010000030C446A",
                  "urn:ucode:_00001C000000000000010000030C446B",
                ],
                "@context": "http://vocab.tokyometroapp.jp/context_odpt_Station.jsonld"
              }
            ]

## 駅施設情報 [/datapoints?rdf:type=odpt:StationFacility&acl%3AconsumerKey={acl%3AconsumerKey}]
駅の施設に関する情報を記述する。

+ Parameters
    + rdf%3Atype                    (required, odpt:TrainInformation, `odpt:TrainInformation`) ... クラス指定
    + acl%3AconsumerKey             (required, acl:ConsumerKey      , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + %40id                           (optional, URN                  , `optional`) ... 固有識別子(ucode)
    + owl%3AsameAs                  (optional, URL                  , `optional`) ... 固有識別子。命名ルールは、odpt.StationFacility:TokyoMetro.駅名 である。

### Response [GET]
#### Response Params

第1階層                  | 第2階層                  | 第3階層                | 値域                   | 説明                                                                                                                                                                                          | 必須
-------------------------|--------------------------|------------------------|------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------
@context                 |                          |                        | URL                    | JSON-LD仕様に基づく @context のURL                                                                                                                                                            | ◯
@id                      |                          |                        | URN                    | 固有識別子(ucode)                                                                                                                                                                             | ◯
@type                    |                          |                        | odpt:StationFacility   | 駅施設情報を表すクラスのodpt:StationFacility                                                                                                                                                  | ◯
owl:sameAs               |                          |                        | URL                    | 固有識別子。命名ルールは、odpt.StationFacility:TokyoMetro.駅名 である。                                                                                                                       | ◯
odpt:barrierfreeFacility |                          |                        | Array(ug:SpatialThing) | 駅の施設一覧                                                                                                                                                                                  |
                         | @id                      |                        | URN                    | 固有識別子(ucode)。一つの施設に複数の別のIDが割り当てられる場合がある                                                                                                                         |
                         | @type                    |                        |                        | バリアフリー施設を表すクラス（"ug:Toilet", "spac:Stairlift", "ug:Elevator", "ug:Escalator", "ug:Link"）                                                                                       |
                         | owl:sameAs               |                        | URL                    | 固有識別子. 命名ルールはodpt.Facility:TokyoMetro.路線名.駅名.改札の内外.カテゴリ名.通し番号 である。                                                                                          |
                         | ugsrv:categoryName       |                        | xsd:string             | 施設のカテゴリ名（トイレ、階段昇降機、エレベータ、エスカレータ、ハンドル型電動車いす利用可能経路）                                                                                            |
                         | odpt:serviceDetail       |                        | Array                  | 施設情報の詳細                                                                                                                                                                                |
                         |                          | ugsrv:serviceStartTime | xsd:string             | 施設の利用可能開始時間（いつでも利用できる場合は省略）。基本的にはISO8601時刻形式（05:30など）であるが、「始発」と入る場合もある。                                                            |
                         |                          | ugsrv:serviceEndTime   | xsd:string             | 施設の利用可能終了時間（いつでも利用できる場合は省略）。基本的にはISO8601時刻形式（23:50など）であるが、「終車時」と入る場合もある。                                                          |
                         |                          | odpt:operationDay      | xsd:string             | 施設利用可能時間やエスカレータの方向が曜日によって変わる場合に、次のいずれかを格納（曜日に依存しない場合は省略） Weekday, Sunday, Monday, Tuesday Wednesday Thursday Friday Saturday, Holiday |
                         |                          | ug:direction           | xsd:string             | エスカレータの方向名（施設がエスカレータの場合に格納。上り、下り、上り・下りの3種類が存在）                                                                                                   |
                         | odpt:placeName           |                        | xsd:string             | 施設の設置されている場所の名前                                                                                                                                                                |
                         | odpt:locatedAreaName     |                        | xsd:string             | 施設の設置場所（改札内／改札外）                                                                                                                                                              |
                         | ugsrv:remark             |                        | xsd:string             | 補足事項                                                                                                                                                                                      |
                         | spac:hasAssistant        |                        | spac:Assistant         | トイレ内のバリアフリー施設を記述。 "spac:WheelchairAssessible", "ug:BabyChangingTable", "spac:Ostomate" が格納される。                                                                        |
                         | spac:isAvailableTo       |                        | spac:MoverType         | ハンドル型電動車いす利用可能経路の場合は"spac:MobilityScooter" が格納される。車いす対応エスカレータの場合は"spac:Wheelchair"が格納される。                                                    |
odpt:platformInformation |                          |                        | Array                  | プラットフォームに車両が停車している時の、車両毎の最寄りの施設・出口等の情報を記述                                                                                                            | ◯
                         | odpt:carComposition      |                        | xsd:integer            | 車両編成数                                                                                                                                                                                    | ◯
                         | odpt:carNumber           |                        | xsd:integer            | 車両の号車番号                                                                                                                                                                                | ◯
                         | odpt:railDirection       |                        | odpt:RailDirection     | プラットフォームに停車する列車の方面                                                                                                                                                          | ◯
                         | odpt:transferInformation |                        | Array                  | 最寄りの乗り換え可能な路線と所要時間                                                                                                                                                          |
                         |                          | odpt:railway           | odpt:Railway           | 乗り換え可能路線                                                                                                                                                                              |
                         |                          | odpt:railDirection     | odpt:RailDirection     | 乗り換え可能路線の方面。乗り換え可能な方面を特記する必要がある場合にのみ記載。                                                                                                                |
                         |                          | odpt:necessaryTime     | xsd:integer            | 所要時間（分）                                                                                                                                                                                |
                         | odpt:barrierfreeFacility |                        | Array(ug:StatialThing) | 最寄りのバリアフリー施設                                                                                                                                                                      |
                         | odpt:surroundingArea     |                        | Array(xsd:string)      | 改札外の最寄り施設                                                                                                                                                                            |

+ Response 200 (application/json)
    + Body

            [
              {
                "@context": "http://vocab.tokyometroapp.jp/context_odpt_StationFacility.jsonld",
                "@id": "urn:ucode:_00001C000000000000010000030C478A",
                "@type": "odpt:StationFacility",
                "owl:sameAs": "odpt.StationFacility:TokyoMetro.KokkaiGijidomae",
                "odpt:barrierfreeFacility": [
                  {
                    "@id": "urn:ucode:_00001C000000000000010000030C493E",
                    "@type": "ug:Elevator",
                    "owl:sameAs": "odpt.StationFacility:TokyoMetro.Marunouchi.KokkaiGijidomae.Inside.Elevator.1",
                    "ugsrv:categoryName": "エレベーター",
                    "odpt:placeName": "１番線、２番線ホーム（第2車両付近）～国会議事堂方面改札",
                    "odpt:locatedAreaName": "改札内",
                  },
                  {
                    "@id": "urn:ucode:_00001C000000000000010000030C4942",
                    "@type": "ug:Escalator",
                    "owl:sameAs": "odpt.StationFacility:TokyoMetro.Marunouchi.KokkaiGijidomae.Outside.Escalator.1",
                    "ugsrv:categoryName": "エスカレーター",
                    "odpt:serviceDetail": [
                      {
                        "odpt:operationDay": "平日",
                        "ugsrv:serviceStartTime": "始発",
                        "ugsrv:serviceEndTime": "17:00",
                        "ug:direction": "上り"
                      },
                      {
                        "odpt:operationDay": "平日",
                        "ugsrv:serviceStartTime": "17:00",
                        "ugsrv:serviceEndTime": "終車時",
                        "ug:direction": "下り"
                      },
                      {
                        "odpt:operationDay": "土日祝",
                        "ug:direction": "上り"
                      }
                    ],
                    "odpt:placeName": "国会議事堂方面改札～１番出入口",
                    "odpt:locatedAreaName": "改札外",
                  },
                  {
                    "@id": "urn:ucode:_00001C000000000000010000030C4943",
                    "@type": "ug:Toilet",
                    "owl:sameAs": "odpt.StationFacility:TokyoMetro.Marunouchi.KokkaiGijidomae.Outside.Toilet.1",
                    "ugsrv:categoryName": "トイレ",
                    "odpt:placeName": "国会議事堂方面改札外",
                    "odpt:locatedAreaName": "改札外",
                    "spac:hasAssistant": [
                      "spac:WheelchairAssesible",
                      "ug:BabyChair",
                      "ug:BabyChangingTable",
                      "ug:ToiletForOstomate"
                    ],
                  },
                  {
                    "@id": "urn:ucode:_00001C000000000000010000030C4944",
                    "@type": "ug:Link",
                    "owl:sameAs": "odpt.StationFacility:TokyoMetro.Marunouchi.KokkaiGijidomae.Outside.AccessibleRoute.1",
                    "ugsrv:categoryName": "ハンドル型電動車いす利用可能経路",
                    "odpt:locatedAreaName": "改札外",
                    "spac:isAvailableTo": "spac:MobilityScooter",
                    "ugsrv:remark": "国会議事堂横2番出入口エレベーターで改札階へお越しください。千代田線の利用および乗り
            換えも可能です。",
                  },
                "odpt:platformInformation": [
                  {
                    "odpt:carComposition": 6,
                    "odpt:carNumber": 1,
                    "odpt:railDirection": "odpt.RailDirection:TokyoMetro.Ikebukuro"
                  },
                  {
                    "odpt:carComposition": 6,
                    "odpt:carNumber": 3,
                    "odpt:railDirection": "odpt.RailDirection:TokyoMetro.Ikebukuro",
                    "odpt:transferInformation": [
                      {
                        "odpt:railway": "odpt.Railway:TokyoMetro.Ginza",
                        "odpt:necessaryTime": 13
                      },
                      {
                        "odpt:railway": "odpt.Railway:TokyoMetro.Chiyoda",
                        "odpt:necessaryTime": 4
                      },
                      {
                        "odpt:railway": "odpt.Railway:TokyoMetro.Namboku",
                        "odpt:necessaryTime": 10
                      }
                    ],
                    "odpt:barrierfreeFacility": [
                      "odpt.StationFacility:TokyoMetro.Marunouchi.KokkaiGijidomae.Outside.Toilet.1"
                    ],
                    "odpt:surroundingArea": [
                      "国会議事堂"
                    ]
                  }
                ]
              }
            ]

## 駅乗降人員数 [/datapoints?rdf:type=odpt:PassengerSurvey&acl%3AconsumerKey={acl%3AconsumerKey}]

+ Parameters
    + rdf%3Atype                    (required, odpt:PassengerSurvey , `odpt:PassengerSurvey`) ... クラス指定
    + acl%3AconsumerKey             (required, acl:ConsumerKey      , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + %40id                           (optional, URN                  , `optional`) ... 固有識別子(ucode)
    + owl%3AsameAs                  (optional, URL                  , `optional`) ... 固有識別子。 命名ルールはodpt.PassengerSurvey:TokyoMetro.駅名.調査年 である。e.g. odpt:PassengerSurvey:TokyoMetro.Tokyo.2013
    + odpt%3Aoperator               (optional, odpt:Operator        , `optional`) ... 運行会社
    + odpt%3AsurveyYear             (optional, xsd:integer          , `optional`) ... 調査年度

### Response [GET]
#### Response Params

Properties                              | 値域                               | 説明                                                                                                                                                                                          | 必須
----------------------------            | -----------------------            | ------------------------------------------------------------------------------------------------------------------------------                                                                | -----
@context                                | URL                                | JSON-LD仕様に基づく @context のURL                                                                                                                                                            | ◯
@id                                     | URN                                | 固有識別子(ucode)                                                                                                                                                                             | ◯
@type                                   | odpt:PassengerSurvey               | クラス名、odpt:PassengerSurvey                                                                                                                                                                | ◯
owl:sameAs                              | URL                                | 固有識別子。 命名ルールは odpt.PassengerSurvey:TokyoMetro.駅名.調査年 である。e.g. odpt:PassengerSurvey:TokyoMetro.Tokyo.2013                                                                 | ◯
odpt:operator                           | odpt:Operator                      | 運行会社                                                                                                                                                                                      | ◯
odpt:surveyYear                         | xsd:integer                        | 調査年度                                                                                                                                                                                      | ◯
odpt:passengerJourneys                  | xsd:integer                        | 駅の1日あたりの平均乗降人員数                                                                                                                                                                 | ◯

+ Response 200 (application/json)
    + Body

            [
              {
                "@id": "urn:ucode:_00001C000000000000010000030C4504",
                "@type": "odpt:PassengerSurvey",
                "owl:sameAs": "odpt.PassengerSurvey:TokyoMetro.Ueno.2013",
                "odpt:operator": "odpt.Operator:TokyoMetro",
                "odpt:surveyYear": 2013,
                "odpt:passengerJourneys": 211539,
                "@context": "http://vocab.tokyometroapp.jp/context_odpt_PassengerSurvey.jsonld"
              }
            ]

## 鉄道路線情報 [/datapoints?rdf:type=odpt:Railway&acl%3AconsumerKey={acl%3AconsumerKey}]
路線情報 odpt:Railwayは、鉄道路線の情報を示す。 運行系統名、駅間所要時間、駅間順序などを加筆・修正したものとなる。

+ Parameters
    + rdf%3Atype        (required, odpt:Railway     , `odpt:Railway`) ... クラス指定
    + acl%3AconsumerKey (required, acl:ConsumerKey  , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + %40id               (optional, URN              , `optional`) ... 固有識別子(ucode)支線には別IDを割り当てる
    + owl%3AsameAs      (optional, URL              , `optional`) ... 固有識別子。命名ルールは、odpt.Railway:TokyoMetro.路線名 である。
    + dc%3Atitle        (optional, xsd:string       , `optional`) ... 運行系統名
    + odpt%3Aoperator   (optional, odpt:Operator    , `optional`) ... 運行会社
    + odpt%3AlineCode   (optional, xsd:string       , `optional`) ... 路線コード

### Response [GET]
#### Response Params

第1階層                                 | 第2階層                            | 値域                      | 説明                                                                                  | 必須
----------------------------------------|------------------------------------|---------------------------|---------------------------------------------------------------------------------------|---
@context                                |                                    | URL                       | JSON-LD仕様に基づく @context のURL                                                    | ◯
@id                                     |                                    | URN                       | 固有識別子(ucode)。支線には別IDを割り当てる                                           | ◯
@type                                   |                                    | odpt:Railway              | 地物のクラス名、odpt:Railway                                                          | ◯
owl:sameAs                              |                                    | URL                       | 固有識別子。命名ルールは、odpt.Railway:TokyoMetro.路線名 である。                     | ◯
dc:title                                |                                    | xsd:string                | 運行系統名                                                                            | ◯
ug:region                               |                                    | odpt:GeoDocument          | 路線形状データをGeojsonで取得するためのURL。取得時にはアクセストークンの付与が必要。  | ◯
odpt:operator                           |                                    | odpt:Operator             | 運行会社                                                                              | ◯
odpt:stationOrder                       |                                    | Array                     | 駅の順序                                                                              | ◯
                                        | odpt:station                       | odpt:Station              | 駅                                                                                    | ◯
                                        | odpt:index                         | xsd:integer               | 駅の順序                                                                              | ◯
odpt:travelTime                         |                                    | Array                     | 駅間の標準所要時間リスト                                                              | ◯
                                        | odpt:fromStation                   | odpt:Station              | 駅間の起点                                                                            | ◯
                                        | odpt:toStation                     | odpt:Station              | 駅間の終点                                                                            | ◯
                                        | odpt:necessaryTime                 | xsd:integer               | 駅間の所要時間（分）                                                                  | ◯
odpt:lineCode                           |                                    | xsd:string                | 路線コードを格納                                                                      | ◯
odpt:womenOnlyCar                       |                                    | Array(odpt:WomenOnlyCar)  | 女性専用車両情報のリスト                                                              |
                                        | odpt:fromStation                   | odpt:Station              | 女性専用車両開始駅                                                                    |
                                        | odpt:toStation                     | odpt:Station              | 女性専用車両終了駅                                                                    |
                                        | odpt:operationDay                  | xsd:string                | 女性専用車両実施曜日                                                                  |
                                        | odpt:availableTimeFrom             | odpt:Time                 | 女性専用車両開始時間                                                                  |
                                        | odpt:availableTimeUntil            | odpt:Time                 | 女性専用車両終了時間                                                                  |
                                        | odpt:carComposition                | xsd:integer               | 車両編成数                                                                            |
                                        | odpt:carNumber                     | Array(xsd:integer)        | 女性専用車両実施車両号車番号                                                          |

+ Response 200 (application/json)
    + Body

## 運賃 [/datapoints?rdf:type=odpt:RailwayFare&acl%3AconsumerKey={acl%3AconsumerKey}&odpt:fromStation={odpt%3AfromStation}&odpt:toStation={odpt%3AtoStation}]
2駅間の運賃を表す。

+ Parameters
    + rdf%3Atype             (required, odpt:RailwayFare , `odpt:RailwayFare`) ... クラス指定
    + acl%3AconsumerKey      (required, acl:ConsumerKey  , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + %40id                  (optional, URN              , `optional`) ... 固有識別子(ucode)
    + owl%3AsameAs           (optional, URL              , `optional`) ... 固有識別子。命名ルールはodpt.RailwayFare:TokyoMetro.出発駅の路線名.出発駅名.TokyoMetro.到着駅の路線名.到着駅名 である。
    + odpt%3Aoperator        (optional, odpt:Operator    , `optional`) ... 運行会社
    + odpt%3AfromStation     (optional, odpt:Station     , `odpt.Station:TokyoMetro.Hanzomon.Shibuya`) ... 駅間の始点駅
    + odpt%3AtoStation       (optional, odpt:Station     , `odpt.Station:TokyoMetro.Hanzomon.OmoteSando`) ... 駅間の終点駅
    + odpt%3AticketFare      (optional, xsd:integer      , `optional`) ... 切符利用時の運賃
    + odpt%3AchildTicketFare (optional, xsd:string       , `optional`) ... 切符利用時の子供運賃
    + odpt%3AicCardFare      (optional, xsd:integer      , `optional`) ... ICカード利用時の運賃
    + odpt%3AchildIcCardFare (optional, xsd:nteger       , `optional`) ... ICカード利用時の子供運賃

### Response [GET]
#### Response Params

Properties                   | 値域                    | 説明                                                                                                                           | 必須
---------------------------- | ----------------------- | ------------------------------------------------------------------------------------------------------------------------------ | -----
@context                     | URL                     | JSON-LD仕様に基づく @context のURL                                                                                             | ◯
@id                          | URN                     | 固有識別子(ucode)                                                                                                              | ◯
@type                        | odpt:RailwayFare        | 運賃を表すクラスのodpt:RailwayFare                                                                                             | ◯
owl:sameAs                   | URL                     | 固有識別子。命名ルールはodpt.RailwayFare:TokyoMetro.出発駅の路線名.出発駅名.TokyoMetro.到着駅の路線名.到着駅名 である。        | ◯
dc:date                      | xsd:dateTime            | データ生成日時（ISO8601 日付時刻形式）                                                                                         | ◯
odpt:operator                | odpt:Operator           | 運行会社                                                                                                                       | ◯
odpt:fromStation             | odpt:Station            | 駅間の始点駅                                                                                                                   | ◯
odpt:toStation               | odpt:Station            | 駅間の終点駅                                                                                                                   | ◯
odpt:ticketFare              | xsd:integer             | 切符利用時の運賃                                                                                                               | ◯
odpt:childTicketFare         | xsd:string              | 切符利用時の子供運賃                                                                                                           | ◯
odpt:icCardFare              | xsd:integer             | ICカード利用時の運賃                                                                                                           | ◯
odpt:childIcCardFare         | xsd:nteger              | ICカード利用時の子供運賃                                                                                                       | ◯

+ Response 200 (application/json)
    + Body

            [
              {
                "@id": "urn:ucode:_00001C000000000000010000030C934A",
                "@type": "odpt:RailwayFare",
                "owl:sameAs": "odpt.RailwayFare:TokyoMetro.Hanzomon.Shibuya.TokyoMetro.Hanzomon.OmoteSando",
                "dc:date": "2014-08-29T16:03:36+09:00",
                "odpt:operator": "odpt.Operator:TokyoMetro",
                "odpt:fromStation": "odpt.Station:TokyoMetro.Hanzomon.Shibuya",
                "odpt:toStation": "odpt.Station:TokyoMetro.Hanzomon.OmoteSando",
                "odpt:ticketFare": 170,
                "odpt:childTicketFare": 90,
                "odpt:icCardFare": 165,
                "odpt:childIcCardFare": 82,
                "@context": "http://vocab.tokyometroapp.jp/context_odpt_RailwayFare.jsonld"
              }
            ]

# Group メトロ地物情報取得・検索API

- 地理情報を使った地理領域による絞込機能を提供するAPI
- 緯度経度などの地理情報を持つデータを扱う
- 必須パラメータ
  
  クエリ          | 説明                                                 | 必須
  ----------------|------------------------------------------------------|---
  rdf:type        | 取得するデータの種別を指定します。rdf:type一覧を参照 | ◯
  lat             | 取得する範囲の中心緯度を指定、10進数表記             | ◯
  lon             | 取得する範囲の中心経度を指定、10進数表記             | ◯
  radius          | 取得する範囲の半径をメートルで指定                   | ◯
  acl:consumerKey | 開発者サイトにて発行されたアクセストークンを指定     | ◯


##地物（駅出入口）情報 [/places?rdf:type=ug:Poi&acl%3AconsumerKey={acl%3AconsumerKey}&lon={lon}&lat={lat}&radius={radius}]

+ Parameters
    + rdf%3Atype             (required, ug:Poi           , `ug:Poi`) ... クラス指定
    + acl%3AconsumerKey      (required, acl:ConsumerKey  , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + %40id                  (optional, URN              , `optional`) ... 固有識別子(ucode)
    + lon                    (required, xsd:double       , `139.705678`) ...  検索範囲の中心点の経度、10進表記
    + lat                    (required, xsd:double       , `35.678156`) ...  検索範囲の中心点の緯度、10進表記
    + radius                 (required, xsd:double       , `500`) ...  検索範囲の半径(m) 

### Response [GET]
#### Response Params

Properties                   | 値域                    | 説明                                                                                                                           | 必須
---------------------------- | ----------------------- | ------------------------------------------------------------------------------------------------------------------------------ | -----
@context                     | URL                     | JSON-LD仕様に基づく @context のURL                                                                                             | ◯
@id                          | URN                     | 固有識別子                                                                                                                     | ◯
@type                        | rdf:type                | 地物のクラス名                                                                                                                 | ◯
geo:long                     | xsd:double              | 代表点の経度、10進表記                                                                                                         | ◯
geo:lat                      | xsd:double              | 代表点の緯度、10進表記                                                                                                         | ◯
ug:region                    | odpt:GetDocument        | 地物の形状データをGeoJSONで取得するためのURL。取得にはアクセストークンの付与が必要。                                           |
ug:floor                     | xsd:double              | 地物の階数（高さ情報）                                                                                                         | ◯
dc:title                     | xsd:string              | 地物名。エレベータには「エレベータ」という文字列を含む。「出入口」の文字列の後に出口番号が続く。                               | ◯
ugsrv:categoryName           | xsd:string              | 地物のカテゴリ（必ず「出入口」となる）                                                                                         | ◯

+ Response 200 (application/json)
    + Body

            [
              {
                "@id": "urn:ucode:_00001C000000000000010000030C46B5",
                "@type": "odpt.Station",
                "owl:sameAs": "odpt.Station:TokyoMetro.Ginza.AoyamaItchome",
                "dc:date": "2014-09-03T11:39:51+09:00",
                "dc:title": "青山一丁目",
                "ug:region": "https://api.tokyometroapp.jp/api/v2/places/urn:ucode:_00001C000000000000010000030C46B5.geojson",
                "odpt:operator": "odpt.Operator:TokyoMetro",
                "odpt:railway": "odpt.Railway:TokyoMetro.Ginza",
                "odpt:connectingRailway": [
                  "odpt.Railway:TokyoMetro.Hanzomon",
                  "odpt.Railway:Toei.Oedo"
                ],
                "odpt:facility": "odpt.StationFacility:TokyoMetro.AoyamaItchome",
                "odpt:passengerSurvey": [
                  "odpt.PassengerSurvey:TokyoMetro.AoyamaItchome.2013",
                  "odpt.PassengerSurvey:TokyoMetro.AoyamaItchome.2012",
                  "odpt.PassengerSurvey:TokyoMetro.AoyamaItchome.2011"
                ],
                "odpt:stationCode": "G04",
                "odpt:exit": [
                  "urn:ucode:_00001C000000000000010000030C3EEE",
                  "urn:ucode:_00001C000000000000010000030C3EEF",
                  "urn:ucode:_00001C000000000000010000030C3EF0",
                  "urn:ucode:_00001C000000000000010000030C3EF1",
                  "urn:ucode:_00001C000000000000010000030C3EF2",
                  "urn:ucode:_00001C000000000000010000030C3EF3",
                  "urn:ucode:_00001C000000000000010000030C3EF4",
                  "urn:ucode:_00001C000000000000010000030C3EF5"
                ],
                "@context": "http://vocab.tokyometroapp.jp/context_odpt_Station.jsonld"
              }
            ]

## 国土交通省国土数値情報 地物（駅）情報 [/places?rdf:type=mlit:Station&acl%3AconsumerKey={acl%3AconsumerKey}&lon={lon}&lat={lat}&radius={radius}]

+ Parameters
    + rdf%3Atype             (required, mlit:Station     , `mlit:Station`) ... クラス指定
    + acl%3AconsumerKey      (required, acl:ConsumerKey  , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + lon                    (required, xsd:double       , `139.764901`) ...  検索範囲の中心点の経度、10進表記
    + lat                    (required, xsd:double       , `35.686727`) ...  検索範囲の中心点の緯度、10進表記
    + radius                 (required, xsd:double       , `200`) ...  検索範囲の半径(m) 

### Response [GET]
#### Response Params

Properties                   | 値域                    | 説明                                                                                                                           | 必須
---------------------------- | ----------------------- | ------------------------------------------------------------------------------------------------------------------------------ | -----
@context                     | URL                     | JSON-LD仕様に基づく @context のURL                                                                                             | ◯
@id                          | URN                     | 固有識別子                                                                                                                     | ◯
@type                        | rdf:type                | 地物のクラス名                                                                                                                 | ◯
geo:long                     | xsd:double              | 代表点の経度、10進表記                                                                                                         | ◯
geo:lat                      | xsd:double              | 代表点の緯度、10進表記                                                                                                         | ◯
ug:region                    | odpt:GetDocument        | 地物の形状データをGeoJSONで取得するためのURL。取得にはアクセストークンの付与が必要。                                           |
ug:floor                     | xsd:double              | 地物の階数（高さ情報）                                                                                                         | ◯
dc:title                     | xsd:string              | 地物名。エレベータには「エレベータ」という文字列を含む。「出入口」の文字列の後に出口番号が続く。                               | ◯
ugsrv:categoryName           | xsd:string              | 地物のカテゴリ（必ず「出入口」となる）                                                                                         | ◯

+ Response 200 (application/json)
    + Body

            [
              {
                "@id": "urn:ucode:_00001C000000000000010000030BDBCF",
                "@type": "mlit:Station",
                "@context": "http://vocab.tokyometroapp.jp/context_mlit_Station.jsonld",
                "mlit:stationName": "蔵前",
                "mlit:railwayName": "12号線大江戸線",
                "mlit:operatorName": "東京都",
                "ug:region": "https://api.tokyometroapp.jp/api/v2/places/urn:ucode:_00001C000000000000010000030BDBCF.geojson"
              },
              {
                "@id": "urn:ucode:_00001C000000000000010000030BDBCF",
                "@type": "mlit:Station",
                "@context": "http://vocab.tokyometroapp.jp/context_mlit_Station.jsonld",
                "mlit:stationName": "蔵前",
                "mlit:railwayName": "12号線大江戸線",
                "mlit:operatorName": "東京都",
                "ug:region": "https://api.tokyometroapp.jp/api/v2/places/urn:ucode:_00001C000000000000010000030BDBCF.geojson"
              },
              {
                "@id": "urn:ucode:_00001C000000000000010000030BDBCF",
                "@type": "mlit:Station",
                "@context": "http://vocab.tokyometroapp.jp/context_mlit_Station.jsonld",
                "mlit:stationName": "蔵前",
                "mlit:railwayName": "12号線大江戸線",
                "mlit:operatorName": "東京都",
                "ug:region": "https://api.tokyometroapp.jp/api/v2/places/urn:ucode:_00001C000000000000010000030BDBCF.geojson"
              },
              {
                "@id": "urn:ucode:_00001C000000000000010000030BDBCF",
                "@type": "mlit:Station",
                "@context": "http://vocab.tokyometroapp.jp/context_mlit_Station.jsonld",
                "mlit:stationName": "蔵前",
                "mlit:railwayName": "12号線大江戸線",
                "mlit:operatorName": "東京都",
                "ug:region": "https://api.tokyometroapp.jp/api/v2/places/urn:ucode:_00001C000000000000010000030BDBCF.geojson"
              }
            ]

## 国土交通省国土数値情報 地物（線路）情報 [/places?rdf:type=mlit:Railway&acl%3AconsumerKey={acl%3AconsumerKey}&lon={lon}&lat={lat}&radius={radius}]

+ Parameters
    + rdf%3Atype             (required, mlit:Railway     , `mlit:Railway`) ... クラス指定
    + acl%3AconsumerKey      (required, acl:ConsumerKey  , `xxxxxxxxxxxxxxxxxxx`) ... APIアクセス用のアクセストークン
    + lon                    (required, xsd:double       , `139.764901`) ...  検索範囲の中心点の経度、10進表記
    + lat                    (required, xsd:double       , `35.686727`) ...  検索範囲の中心点の緯度、10進表記
    + radius                 (required, xsd:double       , `200`) ...  検索範囲の半径(m)

### Response [GET]
#### Response Params

Properties                   | 値域                    | 説明                                                                                                                           | 必須
---------------------------- | ----------------------- | ------------------------------------------------------------------------------------------------------------------------------ | -----
@context                     | URL                     | JSON-LD仕様に基づく @context のURL                                                                                             | ◯
@id                          | URN                     | 固有識別子                                                                                                                     | ◯
@type                        | rdf:type                | 地物のクラス名、mlit:Railway                                                                                                   | ◯
geo:long                     | xsd:double              | 代表点の経度、10進表記                                                                                                         | 
geo:lat                      | xsd:double              | 代表点の緯度、10進表記                                                                                                         | 
ug:region                    | odpt:GeoDocument        | 路線形状データをGeoJSONで取得するURL。取得にはアクセストークンの付与が必要。                                                   | 
mlit:operatorName            | xsd:string              | 運営会社名                                                                                                                     | ◯
mlit:railwayName             | xsd:string              | 路線名                                                                                                                         | ◯

+ Response 200 (application/json)
    + Body

            [
              {
                "@id": "urn:ucode:_00001C000000000000010000030BBAEE",
                "@type": "mlit:Railway",
                "@context": "http://vocab.tokyometroapp.jp/context_mlit_Railway.jsonld",
                "mlit:raiwayName": "北リアス線",
                "mlit:operatorName": "三陸鉄道",
                "ug:region": "https://api.tokyometroapp.jp/api/v2/places/urn:ucode:_00001C000000000000010000030BBAEE.geojson"
              },
              {
                "@id": "urn:ucode:_00001C000000000000010000030BBAEE",
                "@type": "mlit:Railway",
                "@context": "http://vocab.tokyometroapp.jp/context_mlit_Railway.jsonld",
                "mlit:raiwayName": "北リアス線",
                "mlit:operatorName": "三陸鉄道",
                "ug:region": "https://api.tokyometroapp.jp/api/v2/places/urn:ucode:_00001C000000000000010000030BBAEE.geojson"
              },
              {
                "@id": "urn:ucode:_00001C000000000000010000030BBAEE",
                "@type": "mlit:Railway",
                "@context": "http://vocab.tokyometroapp.jp/context_mlit_Railway.jsonld",
                "mlit:raiwayName": "北リアス線",
                "mlit:operatorName": "三陸鉄道",
                "ug:region": "https://api.tokyometroapp.jp/api/v2/places/urn:ucode:_00001C000000000000010000030BBAEE.geojson"
              }
            ]
